SUPER = 's'  # kwarg used to detect if the class is initialising as super() or not
DEFAULT_FPS = 25
PYGAME_EVENTS = ['QUIT', 'ACTIVEEVENT', 'KEYDOWN', 'KEYUP', 'MOUSEMOTION', 'MOUSEBUTTONUP', 'MOUSEBUTTONDOWN',
                 'JOYAXISMOTION', 'JOYBALLMOTION', 'JOYHATMOTION', 'JOYBUTTONUP', 'JOYBUTTONDOWN', 'VIDEORESIZE',
                 'VIDEOEXPOSE']
